CREATE DATABASE etu0126 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'etu0126'@'localhost' IDENTIFIED BY 'kwrmdnou';
GRANT ALL PRIVILEGES ON etu0126.* TO 'etu0126'@'localhost';
FLUSH PRIVILEGES;
